import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import favicon from "@/app/favicon.ico"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "figama to next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        
        </body>
    </html>
  );
}
